name = "Nyamcraft"
author = "Lnvll"
version = "0.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5363de51edddeda98010c9728df23aabfe025f65365a74a717bc7d08074f2bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
