ServerEvents.recipes(event => {
event.remove({output: 'farmersdelight:cabbage_crate'})
event.shaped('farmersdelight:cabbage_crate', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/cabbage'})
event.shapeless('9x croptopia:cabbage',  [ 'farmersdelight:cabbage_crate' ])
event.remove({output: 'farmersdelight:tomato_crate'})
event.shaped('farmersdelight:tomato_crate', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/tomato'})
event.shapeless('9x croptopia:tomato',  [ 'farmersdelight:tomato_crate' ])
event.remove({output: 'farmersdelight:onion_crate'})
event.shaped('farmersdelight:onion_crate', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/onion'})
event.shapeless('9x croptopia:onion',  [ 'farmersdelight:onion_crate' ])
event.shaped('fungidelight:brown_mushroom_crate', [ 'AAA', 'AAA', 'AAA' ], { A: 'minecraft:brown_mushroom'})
event.shaped('fungidelight:inky_cap_mushroom_crate', [ 'AAA', 'AAA', 'AAA' ], { A: 'fungidelight:inky_cap_mushroom'})
event.shaped('fungidelight:morel_mushroom_crate', [ 'AAA', 'AAA', 'AAA' ], { A: 'fungidelight:morel_mushroom'})
event.shaped('fungidelight:red_mushroom_crate', [ 'AAA', 'AAA', 'AAA' ], { A: 'minecraft:red_mushroom'})
event.remove({output: 'farmersdelight:rice_bag'})
event.shaped('farmersdelight:rice_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:seeds/rice'})
event.shapeless('9x farmersdelight:rice',  [ 'farmersdelight:rice_bag' ])
event.shapeless('9x croptopia:rice_seed',  [ 'farmersdelight:rice_bag' ])
})