global.removedItems = [
	"ftbquests:loot_crate_opener",
	//croptopia
	"croptopia:dough",
	"croptopia:hops",
	"croptopia:hops_seed",
	"croptopia:cheese",
	"croptopia:beer",
	"croptopia:grape",
	"croptopia:grape_seed",
	"croptopia:oatmeal",
	//farmerdelight
	"farmersdelight:wheat_dough",
	"farmersdelight:bacon",
	"farmersdelight:cooked_bacon",
	//fungidelight
	"fungidelight:brown_mushroom_crate",
	"fungidelight:inky_cap_mushroom_crate",
	"fungidelight:morel_mushroom_crate",
	"fungidelight:red_mushroom_crate",
	"fungidelight:truffle_crate",
	//farm_and_charm
	"farm_and_charm:scarecrow",
	"farm_and_charm:butter",
	"farm_and_charm:bacon",
	//herbalbrews
	"herbalbrews:tea_leaf_crate",
	//letsdo meadow
	"meadow:alpine_salt",
	//vanilla
	//tomato
	"farmersdelight:tomato",
	"farmersdelight:tomato_seeds",
	"farmersdelight:rotten_tomato",
	"farmersdelight:wild_tomatoes",
	"farm_and_charm:tomato",
	"farm_and_charm:tomato_seeds",
	"farm_and_charm:rotten_tomato",
	"farm_and_charm:wild_tomatoes",
	//cabbage
	"farmersdelight:cabbage_seeds",
	"farmersdelight:wild_cabbages",
	"farmersdelight:cabbage",
	"farmersdelight:cabbage_leaf",
	//lettuce
	"farm_and_charm:lettuce",
	"farm_and_charm:lettuce_seeds",
	"farm_and_charm:wild_lettuce",
	//onion
	"farmersdelight:onion",
	"farmersdelight:wild_onions",
	"farm_and_charm:onion",
	"farm_and_charm:wild_onions",
	//rice
	"farmersdelight:rice_bale",
	"farmersdelight:wild_rice",
	"farmersdelight:rice_panicle",
	"farmersdelight:rice",
	//corn
	"farm_and_charm:kernels",
	"farm_and_charm:corn",
	"farm_and_charm:wild_corn",
	//strawberry
	"farm_and_charm:strawberry_seeds",
	"farm_and_charm:strawberry",
	"farm_and_charm:wild_strawberries",
	//barley
	"farm_and_charm:barley_seeds",
	"farm_and_charm:barley",
	"farm_and_charm:barley_ball",
	"farm_and_charm:wild_barley",
	//json missing
	"farm_and_charm:strawberry_tea_cup",
	"farm_and_charm:nettle_tea_cup",
	"farm_and_charm:ribwort_tea_cup"
]