ServerEvents.tags('item', (event) => {
	event.add('c:foods', 'farm_and_charm:lettuce')
	event.add('c:foods/cabbage', 'farm_and_charm:lettuce')
	event.add('c:foods/leafy_green', 'farm_and_charm:lettuce')
	event.add('c:foods', 'croptopia:cabbage')
	event.add('c:foods/cabbage', 'croptopia:cabbage')
	event.add('c:foods/leafy_green', 'croptopia:cabbage')
	event.add('c:strawberry', 'croptopia:strawberry')
	event.remove('c:strawberry', 'croptopia:strawberry_seed')
	event.add('c:fruits/grape', 'vinery:red_grape')
	event.add('c:fruits/grape', 'vinery:white_grape')
	event.add('c:fruits/grape', 'vinery:savanna_grapes_red')
	event.add('c:fruits/grape', 'vinery:savanna_grapes_white')
	event.add('c:fruits/grape', 'vinery:taiga_grapes_red')
	event.add('c:fruits/grape', 'vinery:taiga_grapes_white')
	event.add('c:fruits/grape', 'vinery:jungle_grapes_red')
	event.add('c:fruits/grape', 'vinery:jungle_grapes_white')
	event.add('c:foods/tomato', 'croptopia:tomato')
	event.add('c:seeds/rice', 'farmersdelight:rice')
})
