ServerEvents.recipes(event => {
event.remove({output: 'farm_and_charm:onion_bag'})
event.shaped('farm_and_charm:onion_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/onion'})
event.shapeless('9x croptopia:onion',  [ 'farm_and_charm:onion_bag' ])
event.remove({output: 'farm_and_charm:corn_bag'})
event.shaped('farm_and_charm:corn_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/corn'})
event.shapeless('9x croptopia:corn',  [ 'farm_and_charm:corn_bag' ])
event.remove({output: 'farm_and_charm:strawberry_bag'})
event.shaped('farm_and_charm:strawberry_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:strawberries'})
event.shapeless('9x croptopia:strawberry',  [ 'farm_and_charm:strawberry_bag' ])
event.remove({output: 'farm_and_charm:lettuce_bag'})
event.shaped('farm_and_charm:lettuce_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/lettuce'})
event.shapeless('9x croptopia:lettuce',  [ 'farm_and_charm:lettuce_bag' ])
event.remove({output: 'farm_and_charm:tomato_bag'})
event.shaped('farm_and_charm:tomato_bag', [ 'AAA', 'AAA', 'AAA' ], { A: '#c:crops/tomato'})
event.shapeless('9x croptopia:tomato',  [ 'farm_and_charm:tomato_bag' ])
})